"""empty message

Revision ID: 146d8505a97c
Revises: d7f1c1414b7c
Create Date: 2022-09-27 20:41:03.740479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146d8505a97c'
down_revision = 'd7f1c1414b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
